function controllerSearchArea(){

	valueResetCommentDeep();
	
	submitRequestOverallEngagement(outputOverallEngagementVal);
	
	submitRequestTotalRespondent(outputRespondentVal);

	submitRequestQuestionsTable(outputQuestionsTable);
	submitRequestCitizenCharterOneScores(outputCitizenCharterOneTable);
	submitRequestCitizenCharterTwoScores(outputCitizenCharterTwoTable);
	submitRequestCitizenCharterThreeScores(outputCitizenCharterThreeTable);		

	submitRequestOverallServRate(outputOverallServRatePieChart);
	submitRequestOverallStronglyAgree(outputOverallStronglyAgreeLineChart);
	submitRequestOverallAgree(outputOverallAgreeLineChart);
	submitRequestOverallNeither(outputOverallNeitherLineChart);
	submitRequestOverallDisagree(outputOverallDisagreeLineChart);
	submitRequestOverallStronglyDisagree(outputOverallStronglyDisagreeLineChart);
	submitRequestOverallNoRating(outputOverallNoRatingLineChart);
	submitRequestAvailedOfficeService(outputAvailedOfficeServiceChart);
	
	submitRequestCommentDetails(outputCommentDetails);	
}